### ISSUE TITLE
Code coverage problem [Solution]

### ISSUE THREAD

**Issue by pglez82** [pglez82/asw2223_0#5]
Code coverage was computed not taking into account the restapi code coverage. This was due to two reasons:

1. A [bug](https://github.com/facebook/jest/issues/9773) in jest (the test runner), that saves the file paths with relative paths instead of absolute. This is a problem in the restapi because the tests were stored in a folder 'tests'.
2. Having two github actions jobs for executing the unitary tests was actually making two different test reports, that when uploaded to SonarCloud, were being overwritten.

In order to solve these two issues, the following changes need to be made:

1. Take outside the tests directory the tests for the restapi. Update the package.json of this module accordingly.
2. Replace the two github actions jobs for the unit tests in only one. This job should install the dependencies and run the tests for both modules (or more if it is the case in your project).  When doing this, we only upload to sonarcloud one test coverage report so everything will work as expected.
```yaml
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci
    - run: npm --prefix restapi ci
    - run: npm --prefix webapp test --coverage --watchAll
    - run: npm --prefix restapi test --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
